import type { AboutProfile } from '@izhar-os/types';

/**
 * The content of the About application.
 *
 * Written to be read at a glance: every entry is short enough to survive being
 * set at display size in a 900px window, and nothing here is padding. The
 * numbers are the ones from `SYSTEM_PROFILE` — this file describes the work,
 * not the operator, so it never restates a name, a role or a status.
 */
export const ABOUT_PROFILE: AboutProfile = {
  positioning:
    'Full stack developer with backend expertise — Golang, Node.js, scalable APIs and microservices at the core, Next.js, React and TypeScript interfaces on top, and AI/LLM systems throughout.',

  introduction: [
    'I build the parts of a product that have to keep working when everything else is on fire: the services behind the interface, the data underneath them, and the contracts that hold the two together — then I build the interface too.',
    'Most of my work lives in Go and Node.js — HTTP and GraphQL APIs, event-driven services, realtime channels — and surfaces through Next.js, React, TypeScript and Angular front ends, with a growing share of it now wired into language models rather than around them.',
  ],

  stats: [
    {
      id: 'experience',
      value: '3+',
      label: 'Years Experience',
      detail: 'Shipping production systems',
      countTo: 3,
    },
    {
      id: 'focus',
      value: 'Full Stack',
      label: 'Engineering Focus',
      detail: 'Interfaces, services, data',
    },
    {
      id: 'ai',
      value: 'AI',
      label: 'LLM Integration',
      detail: 'Agents and semantic search',
    },
    {
      id: 'scale',
      value: 'Scalable',
      label: 'Distributed Systems',
      detail: 'Built to grow sideways',
    },
  ],

  journey: [
    {
      id: 'engineering',
      label: 'Software Engineering',
      detail: 'Fundamentals, product work and the habit of shipping.',
    },
    {
      id: 'backend',
      label: 'Backend Development',
      detail: 'Services, persistence and the systems behind the screen.',
    },
    {
      id: 'apis',
      label: 'Scalable APIs & Microservices',
      detail: 'Clear contracts, independent deploys, boring failure modes.',
    },
    {
      id: 'frontend',
      label: 'Frontend & Full Stack',
      detail: 'Next.js and React interfaces owned end to end, from schema to screen.',
    },
    {
      id: 'realtime',
      label: 'Realtime Systems',
      detail: 'WebSockets, events and state that moves as it happens.',
    },
    {
      id: 'ai',
      label: 'AI / LLM Integration',
      detail: 'Retrieval, agents and models as ordinary backend components.',
    },
  ],

  buildAreas: [
    {
      id: 'backend',
      title: 'Backend Systems',
      summary: 'Scalable APIs, microservices and distributed backend services.',
      icon: 'server',
      accent: 'cyan',
      tags: ['Golang', 'Node.js', 'REST', 'GraphQL'],
    },
    {
      id: 'frontend',
      title: 'Frontend Interfaces',
      summary: 'Server-rendered and single-page interfaces on top of my own APIs.',
      icon: 'interface',
      accent: 'rose',
      tags: ['Next.js', 'React', 'TypeScript', 'Angular'],
    },
    {
      id: 'realtime',
      title: 'Realtime Applications',
      summary: 'WebSockets, event-driven services and realtime communication.',
      icon: 'realtime',
      accent: 'violet',
      tags: ['WebSockets', 'Socket.io', 'Events', 'Queues'],
    },
    {
      id: 'ai',
      title: 'AI-Powered Systems',
      summary: 'LLM integrations, semantic search, agents and intelligent workflows.',
      icon: 'ai',
      accent: 'emerald',
      tags: ['LLM APIs', 'RAG', 'Agents', 'Embeddings'],
    },
    {
      id: 'data',
      title: 'Data & Search',
      summary: 'Relational, document, cache, search and vector storage.',
      icon: 'database',
      accent: 'amber',
      tags: ['PostgreSQL', 'MongoDB', 'Redis', 'OpenSearch'],
    },
    {
      id: 'cloud',
      title: 'Cloud & Infrastructure',
      summary: 'Containers, pipelines and the path from commit to production.',
      icon: 'cloud',
      accent: 'slate',
      tags: ['AWS', 'Azure', 'Docker', 'CI/CD'],
    },
  ],

  /**
   * Emphasis, not proficiency. The values describe how the working week is
   * actually spent; the interface says so out loud rather than presenting them
   * as scores.
   */
  focusAreas: [
    { id: 'backend', label: 'Backend', emphasis: 1, note: 'Services and business logic' },
    { id: 'apis', label: 'APIs', emphasis: 0.94, note: 'REST and GraphQL contracts' },
    { id: 'architecture', label: 'Architecture', emphasis: 0.88, note: 'Boundaries and data flow' },
    { id: 'frontend', label: 'Frontend', emphasis: 0.85, note: 'Next.js, React and Angular UIs' },
    { id: 'realtime', label: 'Realtime', emphasis: 0.8, note: 'Sockets and event streams' },
    { id: 'ai', label: 'AI / LLM', emphasis: 0.74, note: 'Retrieval and agent workflows' },
    { id: 'cloud', label: 'Cloud', emphasis: 0.64, note: 'Deployment and infrastructure' },
  ],

  stack: [
    { id: 'languages', label: 'Languages', items: ['Golang', 'TypeScript', 'JavaScript', 'SQL'] },
    {
      id: 'services',
      label: 'Services',
      items: ['Node.js', 'REST', 'GraphQL', 'gRPC', 'Microservices'],
    },
    {
      id: 'frontend',
      label: 'Frontend',
      items: ['Next.js', 'React', 'Angular', 'Tailwind CSS'],
    },
    {
      id: 'data',
      label: 'Data',
      items: ['PostgreSQL', 'MongoDB', 'Redis', 'OpenSearch', 'Vector DBs'],
    },
    { id: 'ai', label: 'AI', items: ['LLM APIs', 'Semantic search', 'RAG', 'Agents'] },
    { id: 'platform', label: 'Platform', items: ['AWS', 'Azure', 'Docker', 'CI/CD'] },
  ],

  interests: [
    'Agentic backends that call tools instead of returning text',
    'Retrieval quality — the unglamorous half of every AI feature',
    'Go concurrency patterns for realtime workloads',
    'React Server Components and where the API boundary should actually sit',
    'Keeping distributed systems debuggable at 3am',
  ],
};

import type {
  ContactConfig,
  ExperienceItem,
  ResumeData,
  SkillCategory,
  SkillItem,
} from '@izhar-os/types';

export const EXPERIENCES: ExperienceItem[] = [
  {
    id: 'freelance-ai-fullstack',
    role: 'Freelance AI & Full Stack Developer',
    company: 'Independent / Freelance Engineering',
    companyUrl: 'https://github.com/izharqadeer03',
    location: 'Remote / New Delhi, India',
    period: '07/2026 — Present',
    duration: 'Present',
    current: true,
    summary:
      'Freelance engineering specializing in AI development, full-stack web applications, and designing autonomous AI automations and LLM workflows for clients worldwide.',
    focusAreas: [
      'AI / LLM Integrations & Agents',
      'Full-Stack Architecture (Next.js & React)',
      'Backend Microservices (Node.js & Go)',
      'Autonomous Workflow Automation',
      'Semantic Search & Vector Retrieval',
    ],
    achievements: [
      'Building custom AI-powered web applications and autonomous AI automation pipelines using OpenAI, LangChain, and vector retrieval systems.',
      'Developing scalable end-to-end full-stack architectures with Next.js, React, Node.js, and Golang microservices.',
      'Implementing intelligent agent workflows, semantic search, and context-aware business automations.',
      'Designing secure payment integrations, database layers (PostgreSQL, Redis), and low-latency API contracts.',
    ],
    technologies: [
      'OpenAI',
      'LangChain',
      'Next.js',
      'React',
      'Node.js',
      'Golang',
      'Python',
      'PostgreSQL',
      'Redis',
      'Tailwind CSS',
      'AI Automations',
    ],
    metrics: [
      { label: 'Automation Gain', value: '10x' },
      { label: 'API Latency', value: '<45ms' },
      { label: 'Delivery Rate', value: '100%' },
    ],
    relatedProjects: ['lands-and-homes', 'boostai-business-platform'],
  },
  {
    id: 'mobiloitte-technologies',
    role: 'Software Engineer / Backend Engineer',
    company: 'Mobiloitte Technologies',
    companyUrl: 'https://www.mobiloitte.com',
    location: 'New Delhi, India',
    period: '09/2023 — 07/2026',
    duration: '~3 Years (2 yrs 11 mos)',
    current: false,
    summary:
      'Built backend microservices using Golang and Node.js for high-throughput applications across multiple business domains, architecting data layers and integrating AI features.',
    focusAreas: [
      'Node.js backend development',
      'Golang backend development',
      'REST APIs & GraphQL',
      'Microservices',
      'PostgreSQL & MongoDB',
      'Redis / caching / Pub/Sub',
      'WebSockets / real-time systems',
      'AI / LLM integrations',
      'AWS / Azure / Docker / CI/CD',
    ],
    achievements: [
      'Built backend microservices using Golang and Node.js for high-throughput applications across multiple business domains.',
      'Developed and optimized REST and GraphQL APIs, improving response times by ~60% through Redis caching, query optimization, and efficient backend architecture.',
      'Architected and managed data layers using PostgreSQL, MongoDB, and Redis for scalable and low-latency operations.',
      'Implemented secure payment workflows using Stripe and Razorpay with retry handling, idempotency mechanisms, and reconciliation processes.',
      'Built AI-powered backend features using OpenAI and LangChain for semantic search, intelligent automation, and context-aware workflows.',
      'Developed real-time backend functionalities using WebSockets and Redis Pub/Sub for concurrent communication systems.',
      'Followed modular backend architecture patterns (controller → service → repository) to improve maintainability and scalability of applications.',
      'Collaborated with frontend, AI, and product teams to deliver scalable production solutions aligned with business requirements.',
      'Contributed to backend performance optimization, debugging, code reviews, and mentoring junior developers on best practices.',
    ],
    technologies: [
      'Node.js',
      'Golang',
      'Express.js',
      'Gin',
      'REST APIs',
      'GraphQL',
      'Microservices',
      'PostgreSQL',
      'MongoDB',
      'Redis',
      'WebSockets',
      'OpenAI',
      'LangChain',
      'AWS',
      'Azure',
      'Docker',
      'CI/CD',
    ],
    metrics: [
      { label: 'API Response Time', value: '-60%' },
      { label: 'Microservices Uptime', value: '99.98%' },
      { label: 'Architecture', value: 'Controller-Service-Repo' },
    ],
    relatedProjects: [
      'lands-and-homes',
      'boostai-business-platform',
      'practice-management-system',
      'chat-sdk',
      'dekhbhal',
    ],
  },
];

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    id: 'languages',
    name: 'Languages',
    shortName: 'Languages',
    description: 'Core programming languages used across services, tooling, and interfaces.',
    icon: 'code',
    accent: 'amber',
  },
  {
    id: 'backend',
    name: 'Backend Engineering',
    shortName: 'Backend',
    description: 'High-throughput microservices, API servers, and business domain engines.',
    icon: 'server',
    accent: 'cyan',
  },
  {
    id: 'databases-search',
    name: 'Databases & Search',
    shortName: 'Databases',
    description: 'Relational, document, in-memory cache, full-text search, graph, and vector stores.',
    icon: 'database',
    accent: 'emerald',
  },
  {
    id: 'ai-llm',
    name: 'AI / LLM Engineering',
    shortName: 'AI & LLM',
    description: 'LLM agents, vector embeddings, semantic retrieval, and intelligent automation.',
    icon: 'ai',
    accent: 'violet',
  },
  {
    id: 'realtime-distributed',
    name: 'Real-Time / Distributed Systems',
    shortName: 'Real-Time',
    description: 'Low-latency duplex communication, streaming channels, and event-driven architecture.',
    icon: 'realtime',
    accent: 'cyan',
  },
  {
    id: 'cloud-devops',
    name: 'Cloud / DevOps',
    shortName: 'Cloud & DevOps',
    description: 'Containerization, cloud infrastructure, CI/CD automation pipelines, and version control.',
    icon: 'cloud',
    accent: 'slate',
  },
  {
    id: 'frontend',
    name: 'Frontend Development',
    shortName: 'Frontend',
    description: 'Modern component-based user interfaces and reactive web applications.',
    icon: 'interface',
    accent: 'rose',
  },
  {
    id: 'apis-integrations',
    name: 'APIs / Integrations',
    shortName: 'Integrations',
    description: 'Payment systems, third-party communication APIs, and resilient integration contracts.',
    icon: 'terminal',
    accent: 'amber',
  },
];

export const SKILLS: SkillItem[] = [
  // 1. Languages
  {
    id: 'javascript',
    name: 'JavaScript',
    category: 'languages',
    level: 'Core / Advanced',
    years: '3 Years',
    featured: true,
    description: 'Modern ESNext syntax, asynchronous runtime event loop mechanics, V8 optimizations, and web API contracts.',
    architecturalRole: 'Core language for full-stack runtimes, client applications, and serverless handlers',
    contextNote: 'Used extensively in production across Node.js backend services and React/Next.js frontend applications.',
    capabilities: ['Async/Await & Promises', 'Event Loop Optimization', 'ESNext Modules', 'Functional Composition'],
    tags: ['ESNext', 'Event Loop', 'Async/Await', 'V8'],
  },
  {
    id: 'nodejs-lang',
    name: 'Node.js',
    category: 'languages',
    level: 'Core / Advanced',
    years: '3 Years',
    featured: true,
    description: 'Server-side JavaScript runtime for event-driven backend services, asynchronous worker pools, and streaming I/O.',
    architecturalRole: 'Primary backend server runtime for high-concurrency microservices and API gateways',
    contextNote: 'Core engine for production APIs at Mobiloitte and freelance systems.',
    capabilities: ['Streaming I/O', 'Cluster Mode', 'Worker Threads', 'Non-blocking I/O'],
    tags: ['Runtime', 'Event-Driven', 'Streams', 'Async I/O'],
    relatedProjects: ['boostai', 'dekhbhal', 'practice-management'],
  },
  {
    id: 'golang-lang',
    name: 'Golang',
    category: 'languages',
    level: 'Core / Advanced',
    years: '3 Years',
    featured: true,
    description: 'Statically typed, compiled systems language delivering high-throughput concurrency with minimal memory overhead.',
    architecturalRole: 'Core systems language for high-performance microservices, background dispatchers, and low-latency APIs',
    contextNote: 'Primary language for microservice architectures at Mobiloitte.',
    capabilities: ['Goroutines & Channels', 'Memory Efficiency', 'Strict Structs & Interfaces', 'Standard Library HTTP'],
    tags: ['Goroutines', 'Channels', 'Concurrency', 'Static Typing'],
    relatedProjects: ['lands-and-homes', 'chat-sdk'],
  },
  {
    id: 'c-cpp',
    name: 'C/C++',
    category: 'languages',
    level: 'Proficient',
    years: '2+ Years',
    featured: false,
    description: 'Systems programming fundamentals, memory management, pointers, and algorithmic problem solving.',
    architecturalRole: 'Foundational systems engineering and low-level compute understanding',
    contextNote: 'Core engineering foundation and algorithmic optimization background.',
    capabilities: ['Manual Memory Management', 'Pointers & References', 'Data Structures & Algorithms', 'System Calls'],
    tags: ['Memory Management', 'Pointers', 'Algorithms', 'Systems'],
  },
  {
    id: 'python',
    name: 'Python',
    category: 'languages',
    level: 'Proficient',
    years: '2+ Years',
    featured: true,
    description: 'Applied scripting, AI/ML model orchestration, data processing, and automation pipelines.',
    architecturalRole: 'AI pipeline scripting, data transformations, and model integration testing',
    contextNote: 'Used in AI automation workflows and semantic retrieval experiments.',
    capabilities: ['FastAPI Scripting', 'Data Processing', 'Automation Scripts', 'LLM Wrappers'],
    tags: ['FastAPI', 'Automation', 'AI Scripting', 'Data Pipelines'],
    relatedProjects: ['lands-and-homes'],
  },

  // 2. Backend
  {
    id: 'nodejs-backend',
    name: 'Node.js',
    category: 'backend',
    level: 'Core / Advanced',
    years: '3 Years',
    featured: true,
    description: 'High-throughput event-driven server runtime handling concurrent requests with asynchronous event loops.',
    architecturalRole: 'Core backend runtime for API layers and microservice clusters',
    contextNote: 'Architected scalable services serving thousands of active users at Mobiloitte.',
    capabilities: ['Microservices Runtimes', 'Middleware Pipelines', 'Event Loop Tuning', 'Worker Thread Processing'],
    tags: ['Runtime', 'Async Event Loop', 'Middleware', 'Cluster'],
    relatedProjects: ['boostai', 'dekhbhal'],
  },
  {
    id: 'expressjs',
    name: 'Express.js',
    category: 'backend',
    level: 'Core / Advanced',
    years: '3 Years',
    featured: true,
    description: 'Fast, unopinionated minimalist web framework for building robust REST APIs and routing pipelines.',
    architecturalRole: 'API layer routing, authentication middleware, error boundaries, and request validation',
    contextNote: 'Standard backend routing framework across Node.js production codebases.',
    capabilities: ['Middleware Routing', 'Error Handling Pipelines', 'Rate Limiting', 'Authentication Filters'],
    tags: ['Routing', 'Middleware', 'REST Layer', 'Security Headers'],
    relatedProjects: ['boostai', 'dekhbhal'],
  },
  {
    id: 'golang-backend',
    name: 'Golang',
    category: 'backend',
    level: 'Core / Advanced',
    years: '3 Years',
    featured: true,
    description: 'Concurrent backend microservices utilizing lightweight goroutines and channel-based communication.',
    architecturalRole: 'Low-latency microservices with minimal CPU and memory footprints',
    contextNote: 'Developed high-throughput enterprise microservices at Mobiloitte Technologies.',
    capabilities: ['Concurrent Microservices', 'Channel Synchronization', 'Struct Serialization', 'Profiling & Benchmarking'],
    tags: ['Microservices', 'Concurrency', 'Goroutines', 'Low Latency'],
    relatedProjects: ['lands-and-homes', 'chat-sdk'],
  },
  {
    id: 'gin-framework',
    name: 'Gin',
    category: 'backend',
    level: 'Core / Advanced',
    years: '2.5+ Years',
    featured: true,
    description: 'High-performance HTTP web framework written in Go featuring a custom Radix tree router and minimal allocations.',
    architecturalRole: 'High-speed Go API endpoints, validation handlers, and JSON serialization',
    contextNote: 'Preferred web framework for Golang backend services at Mobiloitte.',
    capabilities: ['Radix Tree Routing', 'JSON Binding & Validation', 'Custom Middleware Chains', 'Crash Recovery'],
    tags: ['Go Web Framework', 'Radix Router', 'High Performance', 'JSON Binding'],
    relatedProjects: ['lands-and-homes'],
  },
  {
    id: 'rest-apis',
    name: 'REST APIs',
    category: 'backend',
    level: 'Core / Advanced',
    years: '3 Years',
    featured: true,
    description: 'Standardized HTTP API contracts, stateless endpoints, semantic status codes, idempotent mutations, and pagination.',
    architecturalRole: 'Primary external interface and service-to-service communication protocol',
    contextNote: 'Designed clean, versioned REST endpoints across enterprise and freelance systems.',
    capabilities: ['Resource Modeling', 'Idempotent Operations', 'Cursor/Offset Pagination', 'OpenAPI/Swagger Specs'],
    tags: ['RESTful Design', 'Idempotency', 'HTTP Protocols', 'Pagination'],
    relatedProjects: ['lands-and-homes', 'boostai', 'practice-management', 'dekhbhal'],
  },
  {
    id: 'graphql',
    name: 'GraphQL',
    category: 'backend',
    level: 'Core / Advanced',
    years: '2.5+ Years',
    featured: true,
    description: 'Declarative schema-first query language for APIs, precise field selection, and resolver architectures.',
    architecturalRole: 'Optimized data querying layer reducing over-fetching for web and mobile frontends',
    contextNote: 'Integrated GraphQL schemas for complex domain entities at Mobiloitte.',
    capabilities: ['Schema Definition Language (SDL)', 'Resolvers Architecture', 'N+1 Query Prevention', 'Custom Scalars'],
    tags: ['Schema Design', 'Resolvers', 'Queries & Mutations', 'Declarative Fetching'],
    relatedProjects: ['lands-and-homes', 'dekhbhal'],
  },
  {
    id: 'microservices-arch',
    name: 'Microservices Architecture',
    category: 'backend',
    level: 'Core / Advanced',
    years: '3 Years',
    featured: true,
    description: 'Decoupled domain-driven service boundaries, controller-service-repository patterns, and resilient inter-service communication.',
    architecturalRole: 'System decomposition ensuring independent deployments, fault isolation, and targeted scaling',
    contextNote: 'Built and scaled microservices architectures in production environments.',
    capabilities: ['Domain Separation', 'Controller-Service-Repo Pattern', 'Fault Isolation', 'Distributed Health Checks'],
    tags: ['Distributed Services', 'Domain Boundaries', 'Controller-Service-Repo', 'Scalability'],
    relatedProjects: ['lands-and-homes', 'practice-management'],
  },

  // 3. Databases & Search
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'databases-search',
    level: 'Core / Advanced',
    years: '3 Years',
    featured: true,
    description: 'Enterprise relational database with robust ACID guarantees, JSONB document indexing, complex joins, and query optimization.',
    architecturalRole: 'Primary transactional source of truth for structured application data',
    contextNote: 'Core database across Mobiloitte projects and freelance applications.',
    capabilities: ['ACID Transactions', 'JSONB Indexing & Querying', 'Query Plan Analysis (EXPLAIN)', 'Schema Migrations'],
    tags: ['Relational DB', 'ACID', 'JSONB', 'Query Tuning', 'Indexes'],
    relatedProjects: ['practice-management', 'lands-and-homes', 'boostai'],
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    category: 'databases-search',
    level: 'Proficient',
    years: '2.5+ Years',
    featured: false,
    description: 'Document-oriented NoSQL database for polymorphic records, dynamic schema modeling, and aggregation pipelines.',
    architecturalRole: 'Flexible storage for variable document structures, activity logs, and content models',
    contextNote: 'Used for dynamic document management and healthcare data entities at Mobiloitte.',
    capabilities: ['Aggregation Framework', 'Index Optimization', 'Document Modeling', 'Replica Set Queries'],
    tags: ['NoSQL', 'Document Store', 'Aggregation Pipelines', 'BSON'],
    relatedProjects: ['dekhbhal'],
  },
  {
    id: 'redis',
    name: 'Redis',
    category: 'databases-search',
    level: 'Core / Advanced',
    years: '3 Years',
    featured: true,
    description: 'Ultra-fast in-memory data store for caching, distributed locking (Redlock), session storage, and rate limiting.',
    architecturalRole: 'Low-latency caching layer improving API response times by ~60%',
    contextNote: 'Primary caching and memory layer across all production microservice stacks.',
    capabilities: ['Key Expiration Strategies', 'Distributed Locks', 'Rate Limiting Counters', 'Data Structure Manipulation'],
    tags: ['In-Memory Cache', 'Low Latency', 'Distributed Locks', 'TTL Policies'],
    relatedProjects: ['lands-and-homes', 'boostai', 'chat-sdk'],
  },
  {
    id: 'opensearch',
    name: 'OpenSearch',
    category: 'databases-search',
    level: 'Proficient',
    years: '2+ Years',
    featured: true,
    description: 'Distributed search and analytics engine for inverted-index full-text search, fuzzy matching, and multi-field aggregations.',
    architecturalRole: 'Full-text search engine and structured faceted search for high-volume catalogs',
    contextNote: 'Implemented property and catalog search in production applications.',
    capabilities: ['BM25 Relevance Scoring', 'Faceted Aggregations', 'Custom Analyzers', 'Fuzzy & Prefix Matching'],
    tags: ['Full-Text Search', 'Inverted Index', 'BM25', 'Faceted Search'],
    relatedProjects: ['lands-and-homes'],
  },
  {
    id: 'neo4j',
    name: 'Neo4j',
    category: 'databases-search',
    level: 'Working Knowledge',
    years: '1+ Years',
    featured: false,
    description: 'Native graph database designed to manage connected data structures, nodes, edges, and Cypher query traversals.',
    architecturalRole: 'Modeling complex entity relationships, hierarchy trees, and graph traversal queries',
    contextNote: 'Applied to real estate spatial relationship queries and recommendation graphs.',
    capabilities: ['Cypher Query Language', 'Node & Edge Modeling', 'Graph Traversals', 'Relationship Analytics'],
    tags: ['Graph Database', 'Cypher', 'Connected Data', 'Relationships'],
    relatedProjects: ['lands-and-homes'],
  },
  {
    id: 'pinecone',
    name: 'Pinecone',
    category: 'databases-search',
    level: 'Proficient',
    years: '1.5+ Years',
    featured: true,
    description: 'Managed vector database for dense embedding index storage, cosine similarity calculations, and hybrid metadata filtering.',
    architecturalRole: 'High-speed vector index for semantic search and retrieval-augmented generation (RAG)',
    contextNote: 'Vector store for AI applications and semantic knowledge retrieval.',
    capabilities: ['Cosine Similarity Search', 'Dense Vector Indexing', 'Metadata Filtering', 'Top-K Retrieval'],
    tags: ['Vector Database', 'Embeddings', 'Semantic Index', 'k-NN Search'],
    relatedProjects: ['lands-and-homes'],
  },

  // 4. AI / LLM
  {
    id: 'openai-api',
    name: 'OpenAI',
    category: 'ai-llm',
    level: 'Core / Advanced',
    years: '2+ Years',
    featured: true,
    description: 'Integration with GPT models, structured JSON outputs, function calling, tool use, and streaming completions.',
    architecturalRole: 'Primary LLM inference engine for intelligent extraction, conversational agents, and data analysis',
    contextNote: 'Built AI-powered backend features and automated customer workflows.',
    capabilities: ['Function & Tool Calling', 'Structured JSON Output', 'Streaming Response Buffering', 'Embeddings Generation'],
    tags: ['GPT Models', 'Tool Calling', 'Structured Outputs', 'Streaming'],
    relatedProjects: ['lands-and-homes', 'boostai'],
  },
  {
    id: 'llm-integration',
    name: 'LLM Integration',
    category: 'ai-llm',
    level: 'Core / Advanced',
    years: '2+ Years',
    featured: true,
    description: 'Integrating foundation models into existing backend services, fallback chains, rate handling, and context injection.',
    architecturalRole: 'Bridging backend business logic and database persistence with probabilistic AI systems',
    contextNote: 'Integrated AI capabilities across real estate search, healthcare, and automation products.',
    capabilities: ['Context Window Management', 'Token Optimization', 'Retry & Fallback Strategies', 'Deterministic Validation'],
    tags: ['Model Integration', 'Context Management', 'Prompt Pipelines', 'API Wrappers'],
    relatedProjects: ['lands-and-homes', 'boostai'],
  },
  {
    id: 'ai-powered-apps',
    name: 'AI-powered Applications',
    category: 'ai-llm',
    level: 'Core / Advanced',
    years: '2+ Years',
    featured: true,
    description: 'End-to-end full-stack applications with deeply integrated AI features, intelligent search, and autonomous actions.',
    architecturalRole: 'Delivering end-user value through conversational interfaces, auto-summarization, and smart recommendations',
    contextNote: 'Architected production AI applications including BoostAI and Lands & Homes AI search.',
    capabilities: ['Interactive Chat Interfaces', 'Automated Content Generation', 'Smart Filtering', 'Context-Aware Workflows'],
    tags: ['AI Products', 'Conversational UIs', 'Intelligent Workflows', 'Smart Search'],
    relatedProjects: ['boostai', 'lands-and-homes'],
  },
  {
    id: 'semantic-search',
    name: 'Semantic Search',
    category: 'ai-llm',
    level: 'Core / Advanced',
    years: '2+ Years',
    featured: true,
    description: 'Natural language search querying through vector embeddings, meaning-based matching, and hybrid lexical/semantic ranking.',
    architecturalRole: 'Allowing users to query catalogs using natural language questions rather than strict keywords',
    contextNote: 'Built semantic search pipelines for property listings and knowledge retrieval.',
    capabilities: ['Text Embeddings Pipeline', 'Similarity Ranking', 'Hybrid Search Scoring', 'Query Disambiguation'],
    tags: ['Vector Retrieval', 'Cosine Distance', 'Embeddings', 'Natural Language Search'],
    relatedProjects: ['lands-and-homes'],
  },
  {
    id: 'prompt-engineering',
    name: 'Prompt Engineering',
    category: 'ai-llm',
    level: 'Core / Advanced',
    years: '2+ Years',
    featured: true,
    description: 'Systematic prompt design, few-shot conditioning, system prompt constraints, guardrails, and role definitions.',
    architecturalRole: 'Ensuring predictable, high-accuracy, and safe model responses across all user interactions',
    contextNote: 'Engineered prompts for complex multi-step reasoning and domain-specific structured responses.',
    capabilities: ['Few-Shot Examples', 'Role & Guardrail Specification', 'Structured Extraction Schema', 'Reasoning Step Prompts'],
    tags: ['System Prompts', 'Guardrails', 'Few-Shot', 'JSON Schema Enforcement'],
    relatedProjects: ['boostai', 'lands-and-homes'],
  },
  {
    id: 'langchain',
    name: 'LangChain',
    category: 'ai-llm',
    level: 'Core / Advanced',
    years: '2+ Years',
    featured: true,
    description: 'Orchestration framework for chaining LLM calls, document loaders, text splitters, vector store retrievers, and tools.',
    architecturalRole: 'Structuring multi-step AI reasoning workflows and document retrieval pipelines',
    contextNote: 'Utilized for autonomous AI pipelines and intelligent backend workflows.',
    capabilities: ['Chains & Pipelines', 'Document Chunking', 'Vector Retrievers', 'Custom Tool Definition'],
    tags: ['Orchestration', 'Chains', 'Retrievers', 'Document Loaders'],
    relatedProjects: ['boostai', 'lands-and-homes'],
  },
  {
    id: 'agentic-ai',
    name: 'Agentic AI',
    category: 'ai-llm',
    level: 'Core / Advanced',
    years: '1.5+ Years',
    featured: true,
    description: 'Autonomous goal-driven AI agent architectures with tool invocation, state memory, reflection, and multi-step action execution.',
    architecturalRole: 'Enabling autonomous execution of multi-step business workflows without manual intervention',
    contextNote: 'Developed autonomous AI automation agents for client workflows.',
    capabilities: ['Action Loops & ReAct', 'Tool Invocation Runtimes', 'State Persistence', 'Multi-Agent Coordination'],
    tags: ['Autonomous Agents', 'Tool Calling', 'ReAct Loops', 'State Machines'],
    relatedProjects: ['boostai'],
  },

  // 5. Real-Time / Distributed Systems
  {
    id: 'websockets',
    name: 'WebSockets',
    category: 'realtime-distributed',
    level: 'Core / Advanced',
    years: '2.5+ Years',
    featured: true,
    description: 'Full-duplex persistent bidirectional TCP connections enabling sub-millisecond data transport.',
    architecturalRole: 'Real-time live feeds, notification delivery, and interactive chat messaging',
    contextNote: 'Developed real-time communication modules for healthcare and collaborative platforms.',
    capabilities: ['Persistent TCP Connections', 'Binary & Text Framing', 'Heartbeat Protocols', 'Connection Lifecycle Management'],
    tags: ['Full-Duplex', 'TCP Sockets', 'Low Latency', 'Live Updates'],
    relatedProjects: ['chat-sdk', 'dekhbhal'],
  },
  {
    id: 'socket-io',
    name: 'Socket.io',
    category: 'realtime-distributed',
    level: 'Core / Advanced',
    years: '2.5+ Years',
    featured: true,
    description: 'Event-driven real-time library with automatic HTTP long-polling fallback, room management, and broadcasting.',
    architecturalRole: 'Client-server real-time event broadcasting and channel multiplexing',
    contextNote: 'Integrated Socket.io across Node.js services for real-time room communication.',
    capabilities: ['Room & Namespace Multiplexing', 'Automatic Reconnection', 'Fallback Transport', 'Broadcast Events'],
    tags: ['Socket.io', 'Rooms', 'Namespaces', 'Auto-Reconnect'],
    relatedProjects: ['chat-sdk', 'dekhbhal'],
  },
  {
    id: 'webrtc',
    name: 'WebRTC',
    category: 'realtime-distributed',
    level: 'Proficient',
    years: '1.5+ Years',
    featured: false,
    description: 'Peer-to-peer audio, video, and arbitrary data streaming protocol with ICE/STUN/TURN signaling.',
    architecturalRole: 'Real-time media streaming and peer-to-peer communication channels',
    contextNote: 'Implemented video consultation signaling protocols in healthcare application Dekhbhal.',
    capabilities: ['SDP Offer/Answer Exchange', 'ICE Candidate Handling', 'STUN/TURN Signaling', 'P2P Data Channels'],
    tags: ['P2P Streaming', 'Signaling Server', 'ICE/STUN/TURN', 'Video/Audio'],
    relatedProjects: ['dekhbhal'],
  },
  {
    id: 'event-driven-arch',
    name: 'Event-Driven Architecture',
    category: 'realtime-distributed',
    level: 'Core / Advanced',
    years: '2.5+ Years',
    featured: true,
    description: 'Asynchronous event emitters, producer-consumer models, event sourcing concepts, and decoupled event handling.',
    architecturalRole: 'Decoupled service coordination where producers emit domain events without knowing consumers',
    contextNote: 'Architected event-driven patterns across microservices at Mobiloitte.',
    capabilities: ['Producer-Consumer Patterns', 'Asynchronous Decoupling', 'Idempotent Event Handlers', 'Dead Letter Handling'],
    tags: ['Event-Driven', 'Asynchronous', 'Decoupled', 'Event Handlers'],
    relatedProjects: ['lands-and-homes', 'practice-management'],
  },
  {
    id: 'redis-pubsub',
    name: 'Redis Pub/Sub',
    category: 'realtime-distributed',
    level: 'Core / Advanced',
    years: '2.5+ Years',
    featured: true,
    description: 'Lightweight high-speed messaging broker distributing messages to multiple subscribed channels across instances.',
    architecturalRole: 'Cross-instance broadcast bus synchronizing WebSocket servers across a horizontal cluster',
    contextNote: 'Used to scale WebSocket connections horizontally across multiple server instances.',
    capabilities: ['Multi-Instance Broadcast', 'Channel Pattern Matching', 'Zero-Persistence Fast Delivery', 'Socket Node Sync'],
    tags: ['Pub/Sub', 'Message Bus', 'Horizontal Scaling', 'Broadcast'],
    relatedProjects: ['chat-sdk', 'lands-and-homes'],
  },

  // 6. Cloud / DevOps
  {
    id: 'aws',
    name: 'AWS',
    category: 'cloud-devops',
    level: 'Proficient',
    years: '2+ Years',
    featured: true,
    description: 'Amazon Web Services cloud platform including EC2 compute, S3 object storage, RDS managed databases, and IAM security.',
    architecturalRole: 'Cloud hosting environment for microservice backends, static assets, and managed databases',
    contextNote: 'Deployed and maintained cloud workloads on AWS infrastructure.',
    capabilities: ['EC2 Compute Configuration', 'S3 Bucket Management', 'RDS PostgreSQL/MySQL', 'IAM Roles & Security'],
    tags: ['Cloud Infrastructure', 'EC2', 'S3 Storage', 'RDS', 'IAM'],
    relatedProjects: ['lands-and-homes', 'practice-management'],
  },
  {
    id: 'azure',
    name: 'Azure',
    category: 'cloud-devops',
    level: 'Working Knowledge',
    years: '1.5+ Years',
    featured: false,
    description: 'Microsoft Azure cloud computing services, Virtual Machines, App Services, and Blob storage.',
    architecturalRole: 'Enterprise cloud deployments and Azure cloud service integrations',
    contextNote: 'Deployed enterprise workloads and utilized Azure service endpoints.',
    capabilities: ['Azure App Services', 'Virtual Machine Setup', 'Blob Storage', 'Resource Group Management'],
    tags: ['Azure Cloud', 'App Services', 'Blob Storage', 'Virtual Machines'],
  },
  {
    id: 'docker',
    name: 'Docker',
    category: 'cloud-devops',
    level: 'Core / Advanced',
    years: '3 Years',
    featured: true,
    description: 'Containerization platform for creating lightweight, reproducible service images and multi-container Compose meshes.',
    architecturalRole: 'Packaging services and dependencies into standardized containers for consistent local dev and production deploys',
    contextNote: 'Standardized development and production environments using Docker across all major projects.',
    capabilities: ['Multi-Stage Dockerfiles', 'Docker Compose Meshes', 'Image Optimization (Alpine)', 'Container Networking'],
    tags: ['Containers', 'Docker Compose', 'Multi-Stage Builds', 'Reproducibility'],
    relatedProjects: ['practice-management', 'lands-and-homes', 'dekhbhal'],
  },
  {
    id: 'cicd',
    name: 'CI/CD',
    category: 'cloud-devops',
    level: 'Core / Advanced',
    years: '2.5+ Years',
    featured: true,
    description: 'Continuous Integration & Continuous Deployment pipelines using GitHub Actions for automated linting, testing, and deployment.',
    architecturalRole: 'Automating code validation, test suites, container building, and deployment release stages',
    contextNote: 'Configured GitHub Actions pipelines for automated testing and zero-downtime releases.',
    capabilities: ['GitHub Actions Workflows', 'Automated Lint & Test Gates', 'Container Build & Push', 'Environment Secrets'],
    tags: ['Automation', 'GitHub Actions', 'Pipelines', 'Continuous Delivery'],
  },
  {
    id: 'git',
    name: 'Git',
    category: 'cloud-devops',
    level: 'Core / Advanced',
    years: '3 Years',
    featured: true,
    description: 'Distributed version control system for branch management, code review workflows, rebase strategies, and monorepo management.',
    architecturalRole: 'Source code management, collaboration workflows, versioning, and branch strategies',
    contextNote: 'Daily version control, branch management, pull request reviews, and monorepo hygiene.',
    capabilities: ['Feature Branch Workflows', 'Interactive Rebasing', 'Merge Conflict Resolution', 'Monorepo Tagging'],
    tags: ['Version Control', 'Branching', 'Rebase', 'Code Collaboration'],
  },

  // 7. Frontend
  {
    id: 'reactjs',
    name: 'React.js',
    category: 'frontend',
    level: 'Core / Advanced',
    years: '3 Years',
    featured: true,
    description: 'Component-based declarative UI library for building reactive single-page applications with custom hooks and state machines.',
    architecturalRole: 'Building interactive client-side interfaces and modular UI design systems',
    contextNote: 'Primary frontend library for web application interfaces across multiple production products.',
    capabilities: ['Custom Hooks Architecture', 'Component Composition', 'Context & State Management', 'Memoization & Performance'],
    tags: ['UI Library', 'Custom Hooks', 'Component Lifecycle', 'Virtual DOM'],
    relatedProjects: ['practice-management', 'chat-sdk'],
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    category: 'frontend',
    level: 'Core / Advanced',
    years: '2.5+ Years',
    featured: true,
    description: 'Production React framework featuring App Router, React Server Components (RSC), server actions, and streaming SSR.',
    architecturalRole: 'Full-stack application framework providing SEO optimization, fast initial loads, and secure server-side logic',
    contextNote: 'Engineered full-stack platforms including BoostAI and this IZHAR OS portfolio using Next.js App Router.',
    capabilities: ['App Router & RSC', 'Server Actions', 'SSR & Static Generation', 'API Route Handlers'],
    tags: ['Full-Stack React', 'App Router', 'RSC', 'Server Actions', 'SSR'],
    relatedProjects: ['boostai'],
  },
  {
    id: 'angular',
    name: 'Angular',
    category: 'frontend',
    level: 'Working Knowledge',
    years: '1.5+ Years',
    featured: false,
    description: 'TypeScript-based enterprise web application framework utilizing dependency injection, RxJS observables, and modular architecture.',
    architecturalRole: 'Enterprise frontend development and reactive form handling',
    contextNote: 'Developed frontend modules for the healthcare consultation system Dekhbhal at Mobiloitte.',
    capabilities: ['RxJS Observables', 'Dependency Injection', 'Reactive Forms', 'Modular Architecture'],
    tags: ['Enterprise Framework', 'TypeScript', 'RxJS', 'Dependency Injection'],
    relatedProjects: ['dekhbhal'],
  },

  // 8. APIs / Integrations
  {
    id: 'payment-gateway',
    name: 'Payment Gateway Integration',
    category: 'apis-integrations',
    level: 'Core / Advanced',
    years: '2.5+ Years',
    featured: true,
    description: 'Secure end-to-end payment workflows using Stripe and Razorpay with webhook verification, idempotency keys, and reconciliation.',
    architecturalRole: 'Financial transaction processing, subscription billing, and automated invoice reconciliation',
    contextNote: 'Engineered Stripe & Razorpay payment pipelines with retry handling and idempotency at Mobiloitte.',
    capabilities: ['Stripe & Razorpay APIs', 'Webhook Signature Verification', 'Idempotency Keys', 'Transaction Reconciliation'],
    tags: ['Stripe', 'Razorpay', 'Webhooks', 'Idempotency', 'Payment Security'],
    relatedProjects: ['lands-and-homes', 'practice-management'],
  },
  {
    id: 'google-calendar-api',
    name: 'Google Calendar API',
    category: 'apis-integrations',
    level: 'Proficient',
    years: '2+ Years',
    featured: false,
    description: 'OAuth2 authentication flow, calendar event scheduling, conflict detection, availability syncing, and reminder triggers.',
    architecturalRole: 'Automated consultation scheduling and bidirectional calendar synchronization',
    contextNote: 'Integrated calendar scheduling into practice management and healthcare booking systems.',
    capabilities: ['OAuth2 Token Refresh', 'Event Creation & Rescheduling', 'Free/Busy Availability Checks', 'Webhook Push Notifications'],
    tags: ['Google API', 'OAuth2', 'Scheduling', 'Calendar Sync'],
    relatedProjects: ['practice-management', 'dekhbhal'],
  },
  {
    id: 'zoom-api',
    name: 'Zoom API',
    category: 'apis-integrations',
    level: 'Proficient',
    years: '1.5+ Years',
    featured: false,
    description: 'Server-to-Server OAuth2 integration for creating dynamic video meeting rooms, participant links, and webhook event processing.',
    architecturalRole: 'Automated telemedicine and consultation video room generation',
    contextNote: 'Integrated automated meeting creation in Dekhbhal and practice management platforms.',
    capabilities: ['Server-to-Server OAuth', 'Dynamic Meeting Creation', 'Meeting Webhook Handlers', 'Host / Participant URL Generation'],
    tags: ['Zoom API', 'Video Meetings', 'Server-to-Server OAuth', 'Automated Rooms'],
    relatedProjects: ['dekhbhal'],
  },
  {
    id: 'rest-graphql-api-design',
    name: 'REST / GraphQL API design',
    category: 'apis-integrations',
    level: 'Core / Advanced',
    years: '3 Years',
    featured: true,
    description: 'Contract-first API architecture, semantic error payloads, rate limiting policies, OpenAPI specifications, and schema evolution.',
    architecturalRole: 'Architecting durable, developer-friendly interfaces consumed by web, mobile, and third-party clients',
    contextNote: 'Designed clean API contracts across backend microservices at Mobiloitte.',
    capabilities: ['Contract-First Specification', 'Unified Error Envelope Schema', 'Rate Limiting & Throttling', 'Backward Compatibility'],
    tags: ['API Design', 'OpenAPI/Swagger', 'Contract-First', 'Schema Evolution'],
    relatedProjects: ['lands-and-homes', 'boostai', 'practice-management'],
  },
];

export const RESUME_DATA: ResumeData = {
  name: 'Izhar Qadeer',
  title: 'Full Stack Developer',
  location: 'New Delhi, India',
  email: 'izharqadeer03@gmail.com',
  summary:
    'Full Stack Developer with around 3 years of experience building scalable web applications using React.js, Next.js, Node.js, and Golang. Experienced in designing responsive user interfaces, developing REST and GraphQL APIs, integrating AI-powered features, and building end-to-end applications. Strong understanding of modern frontend frameworks, backend architecture, databases, cloud technologies, and real-time systems.',
  education: [
    {
      institution: 'ABES Institute of Technology (Affiliated to Dr. APJ Abdul Kalam Technical University)',
      degree: 'Bachelor of Technology (B. Tech) — Electronics & Communication Engineering (ECE)',
      period: '08/2019 — 07/2023',
      location: 'Ghaziabad, India',
      details: [
        'Graduated with 8.5 CGPA.',
        'Core coursework: Computer Networks, Operating Systems, Database Systems, Data Structures & Algorithms.',
      ],
    },
  ],
  certifications: [
    {
      name: 'Full Stack Engineering with Go & Distributed Systems',
      issuer: 'Engineering Specialization',
      year: '2023',
    },
    {
      name: 'Generative AI & LLM Application Architecture',
      issuer: 'Deep Learning & Applied AI',
      year: '2024',
    },
  ],
  competencies: [
    {
      category: 'Backend & Systems',
      skills: ['Golang', 'Node.js', 'Express.js', 'Gin', 'REST APIs', 'GraphQL', 'Microservices Architecture'],
    },
    {
      category: 'Frontend & UI',
      skills: ['React.js', 'Next.js', 'HTML5', 'CSS3', 'Tailwind CSS', 'Redux Toolkit'],
    },
    {
      category: 'Databases & Caching',
      skills: ['PostgreSQL', 'MongoDB', 'MySQL', 'Redis (Caching, Pub/Sub)', 'OpenSearch'],
    },
    {
      category: 'AI / LLM & Agents',
      skills: ['OpenAI', 'LangChain', 'Semantic Search', 'Prompt Engineering', 'AI Automations'],
    },
    {
      category: 'Realtime Systems',
      skills: ['WebSockets', 'Socket.io', 'Redis Pub/Sub', 'Event-Driven Architecture'],
    },
    {
      category: 'Cloud & DevOps',
      skills: ['AWS', 'Azure', 'Docker', 'CI/CD Pipelines', 'Git'],
    },
  ],
};

export const CONTACT_CONFIG: ContactConfig = {
  email: 'izharqadeer03@gmail.com',
  location: 'New Delhi, India',
  timezone: 'IST (UTC+5:30) · Flexible for Global Teams & US/EU Overlap',
  availability: {
    status: 'Available',
    notice: 'Open to AI Development, Full Stack Freelancing & Engineering Roles',
    preferredRoles: [
      'Freelance AI & Full Stack Developer',
      'AI Automations & LLM Agent Engineer',
      'Full Stack Software Engineer (Next.js / Node.js / Go)',
      'Backend Microservices Developer',
    ],
  },
  channels: [
    {
      id: 'email',
      label: 'Email',
      value: 'izharqadeer03@gmail.com',
      href: 'mailto:izharqadeer03@gmail.com',
      icon: 'mail',
      copyable: true,
      primary: true,
    },
    {
      id: 'phone',
      label: 'Phone',
      value: '+91 9795900350',
      href: 'tel:+919795900350',
      icon: 'contact',
      copyable: true,
    },
    {
      id: 'github',
      label: 'GitHub',
      value: 'github.com/izharqadeer03',
      href: 'https://github.com/izharqadeer03',
      icon: 'github',
      primary: true,
    },
    {
      id: 'linkedin',
      label: 'LinkedIn',
      value: 'linkedin.com/in/izhar-qadeer-840b3919a',
      href: 'https://linkedin.com/in/izhar-qadeer-840b3919a',
      icon: 'linkedin',
      primary: true,
    },
  ],
  topics: [
    {
      id: 'ai-automation',
      label: 'AI Development & Automations',
      description: 'Custom AI agent pipelines, semantic search, or LLM-driven automations.',
    },
    {
      id: 'fullstack-project',
      label: 'Full Stack & Web Application',
      description: 'Building end-to-end applications using Next.js, React, Node.js, or Go.',
    },
    {
      id: 'job',
      label: 'Engineering Role Opportunity',
      description: 'Discussing full-stack or backend engineering positions.',
    },
    {
      id: 'general',
      label: 'General Inquiry / Say Hello',
      description: 'Questions about architecture, portfolio, or technical collaboration.',
    },
  ],
};

