export {
  ADMIN_SECRET_KEY,
  checkDatabaseConnection,
  DATABASE_ENABLED,
  DATABASE_URL,
  getDatabaseStatus,
  getPgPool,
  getSupabaseAdminClient,
  getSupabaseClient,
  SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY,
  SUPABASE_URL,
  type DatabaseStatus,
} from './client';

export { SCHEMA_SQL } from './schema';
export { runSchemaMigration, seedAllDefaultData } from './seed';

export {
  deleteContactMessage,
  deleteExperience,
  deleteProject,
  deleteProjectCategory,
  deleteSkill,
  deleteSkillCategory,
  fetchAllPortfolioData,
  fetchAboutProfile,
  fetchContactConfig,
  fetchContactMessages,
  fetchExperiences,
  fetchProjectCategories,
  fetchProjects,
  fetchResumeData,
  fetchSkillCategories,
  fetchSkills,
  fetchSystemProfile,
  insertContactMessage,
  updateAboutProfile,
  updateContactConfig,
  updateMessageStatus,
  updateResumeData,
  updateSystemProfile,
  upsertExperience,
  upsertProject,
  upsertProjectCategory,
  upsertSkill,
  upsertSkillCategory,
  type ContactMessage,
} from './queries';
